version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm run test
      - rm -rf node_modules
      - npm install --only=prod
      - zip -r ./.serverless/rest-api.zip .
      - node getPath.js
      - ls -al
      - cat path.txt
      - filepath=`cat path.txt`
      - aws s3 cp .serverless s3://sls-globant-dev/$filepath --recursive
      - aws cloudformation package --template-file ./.serverless/cloudformation-template-update-stack.json --s3-bucket sls-globant-dev --output-template-file packaged-template.json
artifacts:
  type: zip
  files:
    - ./.serverless/cloudformation-template-update-stack.json
    - packaged-template.json